### ISSUE TITLE
Error when using rqlite to work over the net

### ISSUE THREAD

**Issue by tchoulihan** [otoolep/rqlite#37]
Edit: don't bother reading through this, I figured it out, scroll to the bottom comment.

I'm getting a strange error when using rqlite over the net. I'll post my commands for the leader and follower, and then the go error output.

Leader commands:
```
export GOPATH=$PWD
go get github.com/otoolep/rqlite
go get gopkg.in/check.v1;
$GOPATH/bin/rqlite data
```

Follower commands to join: 
```
export GOPATH=$PWD
go get github.com/otoolep/rqlite
go get gopkg.in/check.v1;
$GOPATH/bin/rqlite -join xx.xx.xx.xx:4001 data
```

Note: I tried this twice in a row, and the second time, I didn't get an error, but there was no db.sqlite file for the follower, and the administration showed some weird things. I'll put these below the error output.

leader output:
```
[04/13/15 09:09:46] [INFO] Redirectoring logging to stdout
[04/13/15 09:09:46] [INFO] Raft random seed initialized
[04/13/15 09:09:46] [INFO] Raft commands registered
[04/13/15 09:09:46] [INFO] Initializing Raft Server: data
[04/13/15 09:09:46] [INFO] Loading latest snapshot, if any, from disk
[04/13/15 09:09:46] [EROR] Error loading snapshot: open data/snapshot: no such file or directory
[04/13/15 09:09:46] [INFO] Initializing new cluster
[04/13/15 09:09:46] [INFO] Initializing HTTP server
[04/13/15 09:09:46] [INFO] Listening at http://localhost:4001
panic: assertion failed: leader.elected.at.same.term.0


goroutine 13 [running]:
github.com/goraft/raft._assert(0x8de100, 0x93af70, 0x1f, 0xc208295cb0, 0x1, 0x1)
	/home/tyler/test/src/github.com/goraft/raft/util.go:60 +0xcf
github.com/goraft/raft.(*server).processAppendEntriesRequest(0xc20808cc60, 0xc2082788c0, 0xc2082788c0, 0xc2082788c0)
	/home/tyler/test/src/github.com/goraft/raft/server.go:948 +0x413
github.com/goraft/raft.(*server).leaderLoop(0xc20808cc60)
	/home/tyler/test/src/github.com/goraft/raft/server.go:849 +0x761
github.com/goraft/raft.(*server).loop(0xc20808cc60)
	/home/tyler/test/src/github.com/goraft/raft/server.go:609 +0x444
github.com/goraft/raft.func·007()
	/home/tyler/test/src/github.com/goraft/raft/server.go:470 +0x60
created by github.com/goraft/raft.(*server).Start
	/home/tyler/test/src/github.com/goraft/raft/server.go:471 +0x49e

goroutine 1 [chan receive]:
main.main()
	/home/tyler/test/src/github.com/otoolep/rqlite/main.go:133 +0x71a

goroutine 5 [chan receive]:
code.google.com/p/log4go.ConsoleLogWriter.run(0xc20803a060, 0x7f9b49b28c58, 0xc208044008)
	/home/tyler/test/src/code.google.com/p/log4go/termlog.go:27 +0x7a
created by code.google.com/p/log4go.NewConsoleLogWriter
	/home/tyler/test/src/code.google.com/p/log4go/termlog.go:19 +0x6b

goroutine 7 [syscall]:
os/signal.loop()
	/home/tyler/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/home/tyler/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:27 +0x35

goroutine 21 [IO wait]:
net.(*pollDesc).Wait(0xc208010bc0, 0x72, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010bc0, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208010b60, 0xc2080d5000, 0x1000, 0x1000, 0x0, 0x7f9b49b28ac8, 0xc2082731a8)
	/home/tyler/.gvm/gos/go1.4.2/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208044028, 0xc2080d5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/net/net.go:121 +0xdc
net/http.(*liveSwitchReader).Read(0xc208264728, 0xc2080d5000, 0x1000, 0x1000, 0x2, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc208277360, 0xc2080d5000, 0x1000, 0x1000, 0x2, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc2081db440)
	/home/tyler/.gvm/gos/go1.4.2/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc2081db440, 0xc20829bb0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc2081db440, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc20825bfb0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc20825bfb0, 0x0, 0x0, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc2081db440, 0xc20829e340, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc2082646e0, 0x0, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc2082646e0)
	/home/tyler/.gvm/gos/go1.4.2/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
	/home/tyler/.gvm/gos/go1.4.2/src/net/http/server.go:1751 +0x35e

goroutine 9 [chan receive]:
code.google.com/p/log4go.ConsoleLogWriter.run(0xc20803a1e0, 0x7f9b49b28c58, 0xc208044008)
	/home/tyler/test/src/code.google.com/p/log4go/termlog.go:27 +0x7a
created by code.google.com/p/log4go.NewConsoleLogWriter
	/home/tyler/test/src/code.google.com/p/log4go/termlog.go:19 +0x6b

goroutine 10 [chan receive]:
database/sql.(*DB).connectionOpener(0xc20807e000)
	/home/tyler/.gvm/gos/go1.4.2/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/home/tyler/.gvm/gos/go1.4.2/src/database/sql/sql.go:452 +0x31c

goroutine 11 [IO wait]:
net.(*pollDesc).Wait(0xc208011cd0, 0x72, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208011cd0, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208011c70, 0x0, 0x7f9b49b28ac8, 0xc208273430)
	/home/tyler/.gvm/gos/go1.4.2/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208044138, 0x50d08e, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc208044138, 0x0, 0x0, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc20803a540, 0x7f9b49b2a988, 0xc208044138, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc20803a540, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/net/http/server.go:1718 +0x154
github.com/otoolep/rqlite/server.(*Server).ListenAndServe(0xc208094120, 0x0, 0x0, 0x0, 0x0)
	/home/tyler/test/src/github.com/otoolep/rqlite/server/server.go:294 +0x163e
main.func·002()
	/home/tyler/test/src/github.com/otoolep/rqlite/main.go:128 +0x42
created by main.main
	/home/tyler/test/src/github.com/otoolep/rqlite/main.go:129 +0x62d

goroutine 22 [select]:
net/http.(*persistConn).roundTrip(0xc20824b080, 0xc208273330, 0x0, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/net/http/transport.go:1082 +0x7ad
net/http.(*Transport).RoundTrip(0xc208094360, 0xc20829e680, 0xc2082a0420, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/net/http/transport.go:235 +0x558
net/http.send(0xc20829e680, 0x7f9b49b28eb0, 0xc208094360, 0x28, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/net/http/client.go:219 +0x4fc
net/http.(*Client).send(0xc208094328, 0xc20829e680, 0x28, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/net/http/client.go:142 +0x15b
net/http.(*Client).doFollowingRedirects(0xc208094328, 0xc20829e680, 0x99e1a8, 0x0, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/net/http/client.go:367 +0xb25
net/http.(*Client).Post(0xc208094328, 0xc2082a03c0, 0x28, 0x912370, 0x14, 0x7f9b49b291c0, 0xc208011650, 0xc208011284, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/net/http/client.go:441 +0x10d
github.com/goraft/raft.(*HTTPTransporter).SendAppendEntriesRequest(0xc2080942d0, 0x7f9b49b29370, 0xc20808cc60, 0xc2080113b0, 0xc208278820, 0x0)
	/home/tyler/test/src/github.com/goraft/raft/http_transporter.go:125 +0x4ec
github.com/goraft/raft.(*Peer).sendAppendEntriesRequest(0xc2080113b0, 0xc208278820)
	/home/tyler/test/src/github.com/goraft/raft/peer.go:193 +0x303
github.com/goraft/raft.(*Peer).flush(0xc2080113b0)
	/home/tyler/test/src/github.com/goraft/raft/peer.go:178 +0x29e
github.com/goraft/raft.(*Peer).heartbeat(0xc2080113b0, 0xc2081db6e0)
	/home/tyler/test/src/github.com/goraft/raft/peer.go:163 +0x5de
github.com/goraft/raft.func·005()
	/home/tyler/test/src/github.com/goraft/raft/peer.go:97 +0x79
created by github.com/goraft/raft.(*Peer).startHeartbeat
	/home/tyler/test/src/github.com/goraft/raft/peer.go:98 +0x1ae

goroutine 18 [select]:
net/http.(*persistConn).readLoop(0xc20805c160)
	/home/tyler/.gvm/gos/go1.4.2/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/home/tyler/.gvm/gos/go1.4.2/src/net/http/transport.go:660 +0xc9f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/home/tyler/.gvm/gos/go1.4.2/src/runtime/asm_amd64.s:2232 +0x1

goroutine 19 [select]:
net/http.(*persistConn).writeLoop(0xc20805c160)
	/home/tyler/.gvm/gos/go1.4.2/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/home/tyler/.gvm/gos/go1.4.2/src/net/http/transport.go:661 +0xcbc

goroutine 24 [select]:
github.com/goraft/raft.(*server).send(0xc20808cc60, 0x861ae0, 0xc2082788c0, 0x0, 0x0, 0x0, 0x0)
	/home/tyler/test/src/github.com/goraft/raft/server.go:630 +0x327
github.com/goraft/raft.(*server).AppendEntries(0xc20808cc60, 0xc2082788c0, 0xc20826edc0)
	/home/tyler/test/src/github.com/goraft/raft/server.go:933 +0x48
github.com/goraft/raft.func·001(0x7f9b49b2fb78, 0xc208264960, 0xc20829e750)
	/home/tyler/test/src/github.com/goraft/raft/http_transporter.go:246 +0x29e
net/http.HandlerFunc.ServeHTTP(0xc20802b0c0, 0x7f9b49b2fb78, 0xc208264960, 0xc20829e750)
	/home/tyler/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc20804c320, 0x7f9b49b2fb78, 0xc208264960, 0xc20829e750)
	/home/tyler/test/src/github.com/gorilla/mux/mux.go:98 +0x297
net/http.serverHandler.ServeHTTP(0xc20803a540, 0x7f9b49b2fb78, 0xc208264960, 0xc20829e750)
	/home/tyler/.gvm/gos/go1.4.2/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2082648c0)
	/home/tyler/.gvm/gos/go1.4.2/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/home/tyler/.gvm/gos/go1.4.2/src/net/http/server.go:1751 +0x35e

goroutine 25 [IO wait]:
net.(*pollDesc).Wait(0xc2082a60d0, 0x72, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2082a60d0, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2082a6070, 0xc2082b1000, 0x1000, 0x1000, 0x0, 0x7f9b49b28ac8, 0xc208273478)
	/home/tyler/.gvm/gos/go1.4.2/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208044180, 0xc2082b1000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7f9b49b2aac0, 0xc208044180, 0xc20824b0d8, 0xc2082b1000, 0x1000, 0x1000, 0x7f9b49b17010, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2082777c0, 0xc2082b1000, 0x1000, 0x1000, 0xc207ffbbe7, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc2081dbb60)
	/home/tyler/.gvm/gos/go1.4.2/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc2081dbb60, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/tyler/.gvm/gos/go1.4.2/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc20824b080)
	/home/tyler/.gvm/gos/go1.4.2/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/home/tyler/.gvm/gos/go1.4.2/src/net/http/transport.go:660 +0xc9f

goroutine 26 [select]:
net/http.(*persistConn).writeLoop(0xc20824b080)
	/home/tyler/.gvm/gos/go1.4.2/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/home/tyler/.gvm/gos/go1.4.2/src/net/http/transport.go:661 +0xcbc
```

Second try errors(no db.sqlite file in follower)

leader raft(appears to be correct, except for maybe the connection string)
```
{
    "leader": "229a633",
    "name": "229a633",
    "peers": {
        "3c37b08": {
            "name": "3c37b08",
            "connectionString": "http://localhost:4001"
        }
    },
    "state": "leader"
```

follower raft(shows no leader or peers)
```
{
    "leader": "",
    "name": "3c37b08",
    "peers": null,
    "state": "follower"
}
```

edit: I just tried this on multiple ports(just to make sure forwarding wasn't an issue) and have verified that ports aren't the issue.

**Comment by tchoulihan** [comment]
I think I may have figured it out, I think I have to pass hostnames as -h params for both the follower and leader, I'll double check this a few times.

**Comment by tchoulihan** [comment]
Yep that was the problem.

Both the follower and leader startups need -h xx.xx.xx.xx IP where the xx. is their own external ip address.

Before we close this out, it would be good to put this info on the rqlite readme.md under a heading of *how to use rqlite over the internet* . Let me know if you want me to do a pull request to do this.

**Comment by otoolep** [comment]
I'm not sure I follow you. There is nothing special about the "internet" per-se, but if the hostname automatically picked up by the software is not one that will allow other nodes to connect to it, then you may need to specify the hostname explicitly. When you say external address, what is an internal address? Are you trying this out on AWS?

**Comment by tchoulihan** [comment]
This isn't on AWS, just regular servers.

> There is nothing special about the "internet" per-se, but if the hostname automatically picked up by the software is not one that will allow other nodes to connect to it

This is the case. If you start up rqlite without a `-h my_external_ip`, it will only accept connections from localhost for some reason.

> When you say external address, what is an internal address?

Internal address might be localhost, or a router given ip. External meaning internet ip.

**Comment by otoolep** [comment]
Hmmm. That is strange. 

There is nothing in rqlite that makes any assumptions about the hostname passed in. It'll either use the one it detects, or the one passed in, and doesn't do anything else special. This sounds more like something about your networking setup, how hostnames are resolved, etc etc., nothing to do with rqlite in particular.

**Comment by tchoulihan** [comment]
It's very possible its got something to do with my network setup. It was just something I had to work through, I leave it to you to decide whether to add it to the readme.
